# Every target runs the Go toolchain inside Docker — no local Go required.
# BuildKit is opt-in on Docker 20.10, so enable it for all `docker build` calls
# (needed for the `# syntax` directive and --mount=type=cache in the Dockerfile).
export DOCKER_BUILDKIT := 1

# Go image used for module maintenance; matches the Dockerfile builder.
GO_IMAGE := golang:1.25-bookworm
IMAGE    := voiceline:latest
MODCACHE := voiceline-modcache

# Run a Go command against the working tree with a persistent module cache.
GO_RUN = docker run --rm \
	-v "$(CURDIR)":/src -w /src \
	-v $(MODCACHE):/go/pkg/mod \
	$(GO_IMAGE)

.PHONY: tidy fmt test build up down logs help

help: ## Show available targets
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) \
		| awk 'BEGIN{FS=":.*?## "}{printf "  %-8s %s\n", $$1, $$2}'

# go.sum is generated by `go mod tidy`. Declaring it as a real-file target lets
# test/build/up bootstrap it automatically on a fresh checkout, so a reviewer
# never hits a missing-go.sum error at the Dockerfile COPY step.
go.sum:
	$(GO_RUN) go mod tidy

tidy: ## Resolve dependencies and (re)write go.mod/go.sum
	$(GO_RUN) go mod tidy

fmt: ## Format all Go source with gofmt
	$(GO_RUN) gofmt -w .

test: go.sum ## Run vet + race-enabled unit tests hermetically in Docker
	docker build --target test .

build: go.sum ## Build the distroless runtime image
	docker build --target runtime -t $(IMAGE) .

up: go.sum ## Build and start the service via compose (reads .env)
	docker compose up --build

down: ## Stop and remove the stack
	docker compose down

logs: ## Follow service logs
	docker compose logs -f
